# Generated by Django 4.2.7 on 2023-11-12 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HRAbsence", "0005_alter_user_options_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
