# Generated by Django 4.2.7 on 2023-11-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HRAbsence", "0009_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now=True, verbose_name="date joined"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="last name"),
        ),
    ]
