# Generated by Django 4.2.7 on 2023-11-12 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HRAbsence", "0010_alter_user_date_joined_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
