# Generated by Django 4.2.7 on 2023-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HRAbsence", "0011_remove_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
